apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: order-service
build:
  artifacts:
  - image: order-service
deploy:
  kubectl:
    manifests:
    - k8s/order-service.yaml
portForward:
- resourceType: deployment
  resourceName: order-service
  port: 8080
  localPort: 8080